### PR TITLE
backport: security fix for http-cache-semantics 4.1.1

### LINKED ISSUE #225: [question] security fix for http-cache-semantics 4.1.1 in v8
**Describe the "bug"**

This is not really a bug report but rather a reach out. It seems that the recent PR https://github.com/jaredwray/cacheable-request/pull/224 that mitigates a security vulnerability of the http-cache-semantics (4.1.1) is not present in a release that supports CJS.

I believe this is blocking the adoption of the security fix on got v11 (non-ESM) - https://github.com/sindresorhus/got/issues/2220

I acknowledge that support for [v8 has ended](https://github.com/jaredwray/cacheable-request/blob/main/SECURITY.md) but I'm reaching it as a consultation if it's possible to fix this for the libraries using CJS.

If this is not possible feel free to close the issue.

https://github.com/jaredwray/cacheable-request/security/advisories/GHSA-8x6c-cv3v-vp6g

### PR DESCRIPTION
**Pull request by dscalzi**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/cacheable-request/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Backport #224
Fixes #225 

Could you also update the fixed versions on the security advisory?

### CODE REVIEW

**Comment by phawxby** [comment]
I don't even understand [this advisory](https://github.com/advisories/GHSA-8x6c-cv3v-vp6g), doesn't `^4.1.0` mean compatible with. So consumers of the package can just reinstall dependencies of the package and `4.1.1` would get installed automatically. This advisory and PR would only be needed if it was fixed versioned to `4.1.0`, which it isn't.

**Comment by paulius-valiunas** [comment]
For consumers of this package, their lock file will still keep the version locked to the version before your backport, and by extension, to `http-cache-semantics@4.1.0`, until they run `pnpm update` or similar command. And if they run the command, they will get the new version with or without your backport. In other words, neither this PR nor #224 actually change anything in practice. The only edge cases where this would change anything are:

- Someone already has `http-cache-semantics@4.1.0` in their dependency tree and lock file when they pull in `cacheable-request`. Depending on the package manager, it could remain locked to `4.1.0` and the user would need to update their lock file. That is not an issue you want to be solving - it's standard practice to update your lock file regularly to resolve vulnerabilities.
- Some other package in the user's dependency tree has a fixed (no range) dependency on `http-cache-semantics@4.1.0`. In that case pulling in a new version of `cacheable-request` would add `4.1.1` to their dependency tree but the vulnerable version would still remain there.

**Comment by dscalzi** [comment]
That's my understanding of this as well. I wasn't sure why the original patch was added along with a security disclosure marking the lower versions as vulnerable. This was submitted in an attempt to silence the audit warnings, not necessarily to fix something that's not an issue. If @jaredwray could update or dismiss the disclosure, this could be closed.

**Comment by paulius-valiunas** [comment]
This will not solve the security alert. And as I explained in my above comment, it would not force anyone to be on the patched version.

**Pull request closed without merging**
