### PR TITLE
fix(cacheableRequest): prevent collisions on POST, PUT, and PATCH

### PR DESCRIPTION
**Pull request by elliotttf**
If a server responds with valid cache-control headers POST, PUT, and PATCH requests may be cached. This may lead to cache collisions if the URI is the same between requests. In order to avoid this, this change will hash the body of the request and add that to the cache key. One note: the cache is completely bypassed in the event that the request body is a stream. This is because the key could not be generated without waiting for the stream to end and the contents of the stream may or may not themselves be easily hashed.

### CODE REVIEW

**Comment by lukechilds** [comment]
Hi, sorry for the delay on this! I've been swamped with paid work so had little time for OSS for a while.

Thanks for taking the time to put this together, but I think you're trying to fix a bug that doesn't exist.

Have you found a scenario were this bug exists? If so, can you create a failing test to prove this.

>If a server responds with valid cache-control headers POST, PUT, and PATCH requests may be cached. This may lead to cache collisions if the URI is the same between requests.

Are you saying that a POST to `https://foo.com` might be incorrectly returned as a cached response to a PUT to `https://foo.com`? That won't happen as the cache key is `${opts.method}:${url}` so the keys would be unique, they would be `POST:https://foo.com` and `PUT:https://foo.com`.

https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L44

**Comment by e0ipso** [comment]
@lukechilds our back-end accepts `POST` requests and respond with a 202 and the appropriate cache headers. That is because the entity creation is enqueued for later processing instead of holding the user until the entity is created.

The (immediate) 202 response to the user will depend on the request body. That's why @elliotttf's includes a digestion of the body in the cache key.

I think that it's fair to accept this behavior beyond our particular use case. The cache key is a unique representation of a request, and the request body is an important part of the request. That and the simplicity of the fix I think it's a fair trade-off.

**Comment by adityapatadia** [comment]
I am thinking whether caching of POST, PUT, PATCH request should be allowed at all. As per the protocol, these requests are used to modify something on server and hence most caches and most CDNs bypass cache for such requests. In fact, if this is allowed, it might lead to unexpected behaviour as it is happening in this case.

**Comment by kickbox** [comment]
@adityapatadia There are situations where the behaviour of the POST call is not about modifying data. Even CDN's [allow caching](https://developer.fastly.com/solutions/examples/caching-post-requests) POST calls.

As with any Cache, we must trust that the developer can make the right choice.

**Comment by jaredwray** [comment]
@elliotttf - can you update these to resolve conflicts or do you want me to just close this pull request?

**Comment by elliotttf** [comment]
Yup, sorry, I didn't have a local copy of this since it's been a few years and tried to get away with handling the merge directly in GH 😅

**Pull request merged**
