### PR TITLE
Fix wrong body with 304 responses and forceRefresh

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for the PR!

Can you explain exactly what you think the bug is and how this resolves it?

**Comment by CyberShadow** [comment]
When using `options.forceRefresh=true`, a 304 response from the server will cause cacheable-request to use the server's body, which will be empty for a 304 response.

Have a look at the test if you haven't already. It fails on master, but passes with the patch.

**Comment by CyberShadow** [comment]
@szmarczak Sorry, I don't understand:

- What your "patches" are exactly
- Why I should apply them
- How your suggestion is better than the fix in this pull request
- Whether this is something I *must* address, or if this is just your suggestion.

**Comment by szmarczak** [comment]
> What your "patches" are exactly

Have you seen the review at all?

> Why I should apply them
> How your suggestion is better than the fix in this pull request

You haven't fixed the issue yet.

> Whether this is something I must address, or if this is just your suggestion.

The latter.

#### Why your suggestion does NOT fix the issue?

If you apply the `t.falsy(response.fromCache)` check it gives:

```
  304 responses with forceRefresh do not clobber cache

  /home/szm/Desktop/cacheable-request/test/cache.js:602

   601:     t.falsy(firstResponse.fromCache); 
   602:     t.falsy(secondResponse.fromCache);
   603: });                                   

  Value is not falsy:

  true

```

As per the README:

> Forces refreshing the cache. If the response could be retrieved from the cache, it will perform a new request and override the cache instead.

* :heavy_check_mark: it will perform a new request
* :x: override the cache instead

**Comment by CyberShadow** [comment]
I need forceRefresh to revalidate, so issuing the request but using the cache on 304 is the behavior I expect. If you think forceRefresh should not trust the server's 304 responses at all, then there should be a forceRevalidate option alongside forceRefresh.

**Comment by CyberShadow** [comment]
> Have you seen the review at all?

In your initial wording, you mentioned "patches" as a prerequisite to another suggested change. I see you edited your review now.

> You haven't fixed the issue yet.

As the test shows, the problem as described is fixed. The problem *you* are describing is a different one.

**Comment by szmarczak** [comment]
> there should be a forceRevalidate option alongside forceRefresh.

Seems good to me :)

> you mentioned "patches" as a prerequisite to another suggested change. I see you edited your review now.

I get it now, sorry :P (by patches I meant each diff)

> As the test shows, the problem as described is fixed. The problem you are describing is a different one.

The problem is not fixed because according to the docs cache needs to be overwritten. In this case it isn't, it's just revalidated.

The two-way approach (`forceRevalidate` and `forceRefresh`) would be great :+1: Note that these options are mutually exclusive.

**Pull request closed without merging**
